# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "gridai mnists pytorch"

on:
  push:
    paths:
      - action.yml
      -  pytorch.py
      - .github/workflows/gridai_mnist_pytroch.yml   
  pull_request:  
    paths:
      - action.yml
      -  pytorch.py
      - .github/workflows/gridai_mnist_pytroch.yml    
  schedule:
  # run at 3 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 33 3 * * *

jobs:
  pytorch:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - uses: gridai-actions/gridai-login@main
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}

      - id: gridai-obj-create
        run: |
          cd ${GITHUB_WORKSPACE}
          gridai.py cli "grid run --localdir --instance_type t2.medium --framework torch --dependency_file requirements.txt pytorch.py --max_epochs 3" status_to_kv --gha True
        shell: bash  

      - id: gridai-obj-status
        run: |
          gridai.py run ${{ steps.gridai-obj-create.outputs.grid_name }} --gha True
        shell: bash  

      - run: |
          if [ -z "$(echo ${{ steps.gridai-obj-status.outputs.obj-summary }} | grep 'succeeded')" ]; then
            exit 1
          fi             
        shell: bash  