# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "gridai mnists lightning"

on:
  # push:
  pull_request:  
  schedule:
  # run at 3 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 22 2 * * *

jobs:
  lightning:
    uses: robert-s-lee/actions/gridai_run.yml@main
    with:
      script_name: plmnist.py
      grid_args: --localdir --instance_type t2.medium --dependency_file requirements.txt --framework lightning
      script_args: --max_epochs 3	
    secrets:
      username: ${{ secrets.GRIDAI_USERNAME }}
      key: ${{ secrets.GRIDAI_KEY }}