# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: "gridai cifar10 lightning"

on:
  # push:
  pull_request:  
  schedule:
  # run at 3 min past the hour every day
  # MIN HOUR DOM MON DOW CMD
    - cron: 01 0 * * *

jobs:
  lightning:
    uses: robert-s-lee/actions/.github/workflows/gridai_run_artifact.yml@main
    with:
      script-name: plcifar10.py
      grid-args: --localdir --instance_type t2.medium --dependency_file requirements.txt --framework lightning
      script-args: --max_epochs 3	
    secrets:
      gridai-username: ${{ secrets.GRIDAI_USERNAME }}
      gridai-key: ${{ secrets.GRIDAI_KEY }}